### ISSUE TITLE
[Linux:graphics-info] Implement

### ISSUE THREAD

**Issue by pierremoreau** [Peter-Moller/system-info#6]
Implement something similar to what is done on macOS.
For example, using `lspci -v | awk '/VGA|3D/,/^$/'` would list all GPUs as well as some extra information, such as current driver in use. It sadly does not contain the amount of VRAM, but some (most?) drivers output it either in dmesg or Xorg.0.log.

**Comment by pierremoreau** [comment]
Hum… I guess you were not intending on closing all those issues! :-D Having something like "Fix #X" or "Fixes #X" in your commit message will automatically close the corresponding issue, once pushing that commit to master.

**Comment by Peter-Moller** [comment]
Closed erroneously

**Comment by pierremoreau** [comment]
It is now mostly implemented.
