### ISSUE TITLE
[General] Question: virtual?

### ISSUE THREAD

**Issue by Peter-Moller** [Peter-Moller/system-info#9]
Is it possible to detect weather a machine is a virtual one? Be it VMware, Xen or any other VM system?
It would be an interesting information to display!

**Comment by Peter-Moller** [comment]
On Linux, one may do several things:

1. (ordinary user) If you get any output from this, you are running in a virtual world:
grep "^flags.*\ hypervisor\ " /proc/cpuinfo

2. (root) The command “virt-what” will tell you the name of the VM, if any. 
Example: vmware

3. (root) The following will give you the name:
dmidecode -t system|grep 'Manufacturer\|Product'
	Manufacturer: VMware, Inc.
	Product Name: VMware Virtual Platform
or rather:
dmidecode -s system-product-name
VMware Virtual Platform

4. (ordinary user) The following will give you the answer:
dmesg |grep -i hypervisor
[    0.000000] Hypervisor detected: VMware
[    0.000000] TSC freq read from hypervisor : 2599.998 MHz
[    1.014620] [drm] Max dedicated hypervisor surface memory is 0 kiB

Also, one might look at PID 1. On a “real” machine, it should be “init” (on VMware it's “systemd”).

Docker may be a problem, though!

Useful URL: 
http://unix.stackexchange.com/questions/3685/find-out-if-the-os-is-running-in-a-virtual-environment
http://unix.stackexchange.com/questions/89714/easy-way-to-determine-virtualization-technology

**Comment by pierremoreau** [comment]
@Peter-Moller This one has been implemented, hasn't it?

**Comment by Peter-Moller** [comment]
This has been done
